# Generated by Django 4.2.11 on 2024-04-22 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("calc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("add", "Addition"),
                            ("subtract", "Subtraction"),
                            ("multiply", "Multiplication"),
                            ("divide", "Division"),
                        ],
                        max_length=20,
                    ),
                ),
                ("operand1", models.FloatField()),
                ("operand2", models.FloatField()),
                ("result", models.FloatField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
    ]
